require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MoralPersonsController do

  def mock_moral_person(stubs={})
    @mock_moral_person ||= mock_model(MoralPerson, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all moral_persons as @moral_persons" do
      MoralPerson.stub(:all) { [mock_moral_person] }
      get :index
      assigns(:moral_persons).should eq([mock_moral_person])
    end
  end

  describe "GET show" do
    it "assigns the requested moral_person as @moral_person" do
      MoralPerson.stub(:find).with("37") { mock_moral_person }
      get :show, :id => "37"
      assigns(:moral_person).should be(mock_moral_person)
    end
  end

  describe "GET new" do
    it "assigns a new moral_person as @moral_person" do
      MoralPerson.stub(:new) { mock_moral_person }
      get :new
      assigns(:moral_person).should be(mock_moral_person)
    end
  end

  describe "GET edit" do
    it "assigns the requested moral_person as @moral_person" do
      MoralPerson.stub(:find).with("37") { mock_moral_person }
      get :edit, :id => "37"
      assigns(:moral_person).should be(mock_moral_person)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created moral_person as @moral_person" do
        MoralPerson.stub(:new).with({'these' => 'params'}) { mock_moral_person(:save => true) }
        post :create, :moral_person => {'these' => 'params'}
        assigns(:moral_person).should be(mock_moral_person)
      end

      it "redirects to the created moral_person" do
        MoralPerson.stub(:new) { mock_moral_person(:save => true) }
        post :create, :moral_person => {}
        response.should redirect_to(moral_person_url(mock_moral_person))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved moral_person as @moral_person" do
        MoralPerson.stub(:new).with({'these' => 'params'}) { mock_moral_person(:save => false) }
        post :create, :moral_person => {'these' => 'params'}
        assigns(:moral_person).should be(mock_moral_person)
      end

      it "re-renders the 'new' template" do
        MoralPerson.stub(:new) { mock_moral_person(:save => false) }
        post :create, :moral_person => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested moral_person" do
        MoralPerson.stub(:find).with("37") { mock_moral_person }
        mock_moral_person.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :moral_person => {'these' => 'params'}
      end

      it "assigns the requested moral_person as @moral_person" do
        MoralPerson.stub(:find) { mock_moral_person(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:moral_person).should be(mock_moral_person)
      end

      it "redirects to the moral_person" do
        MoralPerson.stub(:find) { mock_moral_person(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(moral_person_url(mock_moral_person))
      end
    end

    describe "with invalid params" do
      it "assigns the moral_person as @moral_person" do
        MoralPerson.stub(:find) { mock_moral_person(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:moral_person).should be(mock_moral_person)
      end

      it "re-renders the 'edit' template" do
        MoralPerson.stub(:find) { mock_moral_person(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested moral_person" do
      MoralPerson.stub(:find).with("37") { mock_moral_person }
      mock_moral_person.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the moral_persons list" do
      MoralPerson.stub(:find) { mock_moral_person }
      delete :destroy, :id => "1"
      response.should redirect_to(moral_persons_url)
    end
  end

end
