require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe NaturalPersonsController do

  def mock_natural_person(stubs={})
    @mock_natural_person ||= mock_model(NaturalPerson, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all natural_persons as @natural_persons" do
      NaturalPerson.stub(:all) { [mock_natural_person] }
      get :index
      assigns(:natural_persons).should eq([mock_natural_person])
    end
  end

  describe "GET show" do
    it "assigns the requested natural_person as @natural_person" do
      NaturalPerson.stub(:find).with("37") { mock_natural_person }
      get :show, :id => "37"
      assigns(:natural_person).should be(mock_natural_person)
    end
  end

  describe "GET new" do
    it "assigns a new natural_person as @natural_person" do
      NaturalPerson.stub(:new) { mock_natural_person }
      get :new
      assigns(:natural_person).should be(mock_natural_person)
    end
  end

  describe "GET edit" do
    it "assigns the requested natural_person as @natural_person" do
      NaturalPerson.stub(:find).with("37") { mock_natural_person }
      get :edit, :id => "37"
      assigns(:natural_person).should be(mock_natural_person)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created natural_person as @natural_person" do
        NaturalPerson.stub(:new).with({'these' => 'params'}) { mock_natural_person(:save => true) }
        post :create, :natural_person => {'these' => 'params'}
        assigns(:natural_person).should be(mock_natural_person)
      end

      it "redirects to the created natural_person" do
        NaturalPerson.stub(:new) { mock_natural_person(:save => true) }
        post :create, :natural_person => {}
        response.should redirect_to(natural_person_url(mock_natural_person))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved natural_person as @natural_person" do
        NaturalPerson.stub(:new).with({'these' => 'params'}) { mock_natural_person(:save => false) }
        post :create, :natural_person => {'these' => 'params'}
        assigns(:natural_person).should be(mock_natural_person)
      end

      it "re-renders the 'new' template" do
        NaturalPerson.stub(:new) { mock_natural_person(:save => false) }
        post :create, :natural_person => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested natural_person" do
        NaturalPerson.stub(:find).with("37") { mock_natural_person }
        mock_natural_person.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :natural_person => {'these' => 'params'}
      end

      it "assigns the requested natural_person as @natural_person" do
        NaturalPerson.stub(:find) { mock_natural_person(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:natural_person).should be(mock_natural_person)
      end

      it "redirects to the natural_person" do
        NaturalPerson.stub(:find) { mock_natural_person(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(natural_person_url(mock_natural_person))
      end
    end

    describe "with invalid params" do
      it "assigns the natural_person as @natural_person" do
        NaturalPerson.stub(:find) { mock_natural_person(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:natural_person).should be(mock_natural_person)
      end

      it "re-renders the 'edit' template" do
        NaturalPerson.stub(:find) { mock_natural_person(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested natural_person" do
      NaturalPerson.stub(:find).with("37") { mock_natural_person }
      mock_natural_person.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the natural_persons list" do
      NaturalPerson.stub(:find) { mock_natural_person }
      delete :destroy, :id => "1"
      response.should redirect_to(natural_persons_url)
    end
  end

end
